#!/usr/bin/env python3
"""Build the static site published to GitHub Pages.

GitHub Pages serves files, not Python — so the hosted build cannot run the
fan-out search. What it *can* do, entirely in the browser, is the two halves of
this project that are pure data and pure functions:

  * the shipping resolver (deliverable f) — identical logic, ported to JS;
  * the marketplace catalogue (deliverable a) — 64 sites with rationale;
  * a search launcher that folds your query into every marketplace's real
    search URL, which is deliverables (c)/(d) minus the aggregation.

Live aggregated results need the FastAPI backend; the page has a field for its
URL so a locally-run (or self-hosted) backend lights the static site up.

Search links are generated by asking the *real engines* for their URLs with a
sentinel query, so the hosted build can never drift from what the app does.

Outputs:
  site/data.json        catalogue + shipping data for the page
  site/standalone.html  the whole thing inlined into one file (works on file://)
  site/artifact.html    the same, minus the document wrapper, for hosts that
                        supply their own <head>/<body>
"""

from __future__ import annotations

import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
sys.path.insert(0, str(ROOT / "backend"))

import httpx  # noqa: E402

from ufeu import shipping  # noqa: E402
from ufeu.adapters import build_engine  # noqa: E402
from ufeu.adapters.ebay import _MARKETPLACE_COUNTRY, _SITE_HOST  # noqa: E402
from ufeu.catalog import load_catalog  # noqa: E402
from ufeu.models import SearchQuery  # noqa: E402

# A single lowercase alnum word survives percent-encoding, slugification and
# dash-joining unchanged, so it round-trips through every engine's URL builder.
SENTINEL = "queryplaceholder"
PLACEHOLDER = "%QUERY%"


def search_template(market, client) -> dict[str, str] | None:
    engine = build_engine(market, client, {})
    url = engine.build_search_url(SearchQuery(q=SENTINEL, limit=24))
    if SENTINEL not in url:
        return None
    return {"url": url.replace(SENTINEL, PLACEHOLDER), "encoding": engine.query_encoding}


def build_data() -> dict:
    catalog = load_catalog()
    ship = shipping._data()
    client = httpx.Client()

    marketplaces = []
    for market in catalog.marketplaces:
        template = search_template(market, client)
        if template is None:
            continue

        entry = {
            "id": market.id,
            "name": market.name,
            "country": market.country,
            "rank": market.rank,
            "scope": market.scope,
            "site": market.site,
            "focus": market.focus,
            "engine": market.engine,
            "enabled": market.default_enabled,
            "confidence": market.confidence,
            "why": " ".join((market.why or "").split()),
            "ships_to_pt": market.shipping.native_to_pt,
            "shipping_notes": " ".join((market.shipping.notes or "").split()) or None,
            "account": {
                "kind": market.account.kind,
                "required": market.account.required_for_search,
                "signup_url": market.account.signup_url,
                "signup_method": market.account.signup_method,
                "captcha": market.account.captcha,
                "notes": " ".join((market.account.notes or "").split()) or None,
            },
            "search": template,
        }

        # eBay is one catalogue entry but nine national storefronts. Split it so
        # the launcher can offer each country its own link.
        if market.engine == "ebay_browse":
            for marketplace_id in market.engine_config.get("marketplaces", []):
                host = _SITE_HOST.get(marketplace_id)
                country = _MARKETPLACE_COUNTRY.get(marketplace_id)
                if not host or not country:
                    continue
                marketplaces.append({
                    **entry,
                    "id": f"ebay_{country.lower()}",
                    "name": f"eBay {country}",
                    "country": country,
                    "scope": "national",
                    "rank": 2,
                    "site": f"https://www.{host}",
                    "derived_from": "ebay",
                    "search": {
                        "url": f"https://www.{host}/sch/i.html?_nkw={PLACEHOLDER}&LH_ItemCondition=4",
                        "encoding": "component",
                    },
                })
            continue

        marketplaces.append(entry)

    countries = {
        code: {
            "name": country.name,
            "currency": country.currency,
            "zone": shipping.zone_for(code),
        }
        for code, country in catalog.countries.items()
    }

    return {
        "generated": date.today().isoformat(),
        "catalog_updated": catalog.updated,
        "countries": countries,
        "marketplaces": sorted(marketplaces, key=lambda m: (m["country"], m["rank"], m["name"])),
        "shipping": {
            "zones": ship["zones"],
            "zone_costs": {str(k): v for k, v in ship["zone_costs"].items()},
            "strategies": ship["strategies"],
            # Python regexes, lowercase, `\b`-anchored — all valid JS RegExp.
            "weight_hints": [[pattern, kg, bulky] for pattern, kg, bulky in shipping._WEIGHT_HINTS],
            "default_weight_kg": shipping._DEFAULT_WEIGHT,
        },
    }


def inline_standalone(data: dict) -> str:
    """Fold index.html, styles.css, app.js and data.json into one file.

    Useful three ways: it opens straight off the filesystem with no server, it
    is what gets published as a shareable artifact, and it makes the whole tool
    one file you can email to yourself.
    """
    html = (SITE / "index.html").read_text(encoding="utf-8")
    css = (SITE / "styles.css").read_text(encoding="utf-8")
    js = (SITE / "app.js").read_text(encoding="utf-8")

    html = html.replace(
        '<link rel="stylesheet" href="styles.css">',
        f"<style>\n{css}\n</style>",
    )
    # </script> inside a JSON string would close the tag early.
    blob = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    html = html.replace(
        '<script src="app.js"></script>',
        f'<script>window.UFEU_DATA = {blob};</script>\n<script>\n{js}\n</script>',
    )
    return html


def strip_document_wrapper(html: str) -> str:
    """Body content plus <title>, for hosts that wrap pages in their own shell."""
    title = re.search(r"<title>(.*?)</title>", html, re.S)
    head = re.search(r"<head[^>]*>(.*?)</head>", html, re.S)
    body = re.search(r"<body[^>]*>(.*)</body>", html, re.S)

    # The stylesheet is inlined into <head>, which this variant discards — carry
    # the <style> blocks across or the page ships unstyled.
    styles = re.findall(r"<style[^>]*>.*?</style>", head.group(1), re.S) if head else []
    inner = body.group(1) if body else html
    parts = []
    if title:
        # Hosts that show this in a gallery want the product name alone; the
        # descriptive half of the page title is an explainer, not a name.
        parts.append(f"<title>{title.group(1).split(' — ')[0]}</title>")
    parts.extend(styles)
    parts.append(inner.strip())
    return "\n".join(parts) + "\n"


def main() -> int:
    data = build_data()
    # Generated payload, not a file anyone reads or diffs — ship it compact.
    (SITE / "data.json").write_text(
        json.dumps(data, ensure_ascii=False, separators=(",", ":")), encoding="utf-8"
    )

    standalone = inline_standalone(data)
    (SITE / "standalone.html").write_text(standalone, encoding="utf-8")
    (SITE / "artifact.html").write_text(strip_document_wrapper(standalone), encoding="utf-8")

    missing = [m["id"] for m in data["marketplaces"] if PLACEHOLDER not in m["search"]["url"]]
    assert not missing, f"marketplaces with no usable search link: {missing}"

    print(f"site/data.json        {len(data['marketplaces'])} marketplaces, "
          f"{len(data['shipping']['strategies'])} shipping strategies")
    print(f"site/standalone.html  {len(standalone) // 1024} KB, self-contained")
    print(f"site/artifact.html    {len((SITE / 'artifact.html').read_text()) // 1024} KB, no document wrapper")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
