#!/usr/bin/env python3
"""Regenerate docs/01-marketplaces.md from the catalogue, so the prose cannot
drift away from what the code actually searches."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from ufeu.catalog import load_catalog  # noqa: E402
from ufeu.shipping import zone_for     # noqa: E402

EU27 = [
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR",
    "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK",
    "SI", "ES", "SE",
]


def main() -> int:
    catalog = load_catalog()
    lines: list[str] = [
        "# (a) The most-used second-hand marketplace in each EU country",
        "",
        "<!-- GENERATED by scripts/generate_marketplace_doc.py — edit",
        "     backend/ufeu/data/marketplaces.yaml instead. -->",
        "",
        f"Catalogue version {catalog.version}, last reviewed {catalog.updated}. ",
        f"{len(catalog.marketplaces)} marketplaces across {len(EU27)} member states plus the pan-EU players.",
        "",
        "**How to read this.** Rank 1 is what locals reach for first. *Searched by",
        "default* means the app queries it on every search; the rest are one toggle",
        "away. *Confidence* is how sure we are of the \"most used\" claim — medium and",
        "low entries are worth re-checking before you trust them. *Engine* `manual`",
        "means the site is deliberately not automated (bot protection or terms of",
        "service) and the app gives you a deep search link instead.",
        "",
        "## Summary table",
        "",
        "| Country | Zone | #1 platform(s) | Engine | Ships to PT |",
        "| --- | --- | --- | --- | --- |",
    ]

    for code in sorted(EU27, key=lambda c: catalog.countries[c].name):
        country = catalog.countries[code]
        # Several countries genuinely have co-leaders — leboncoin owns French
        # general goods while Vinted owns French fashion — so list them all
        # rather than letting alphabetical order pick a misleading winner.
        tops = [m for m in catalog.for_country(code) if m.rank == 1]
        if not tops:
            continue
        lines.append(
            f"| {country.name} ({code}) | {zone_for(code)} "
            f"| {', '.join(f'[{m.name}]({m.site})' for m in tops)} "
            f"| {', '.join(sorted({f'`{m.engine}`' for m in tops}))} "
            f"| {'yes' if any(m.shipping.native_to_pt for m in tops) else 'no'} |"
        )

    lines += ["", "## Pan-European", ""]
    for market in sorted((m for m in catalog.marketplaces if m.scope == "pan_eu"), key=lambda m: m.rank):
        lines += _entry(market)

    lines += ["", "## Country by country", ""]
    for code in sorted(EU27, key=lambda c: catalog.countries[c].name):
        country = catalog.countries[code]
        markets = catalog.for_country(code)
        if not markets:
            continue
        lines += [
            f"### {country.name} ({code})",
            "",
            f"Currency {country.currency} · shipping zone {zone_for(code)} to Portugal.",
            "",
        ]
        for market in markets:
            lines += _entry(market)

    out = ROOT / "docs" / "01-marketplaces.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


def _entry(market) -> list[str]:
    flags = [f"`{market.engine}`", f"{market.confidence} confidence"]
    if market.default_enabled:
        flags.append("**searched by default**")
    if market.shipping.native_to_pt:
        flags.append("ships to PT")
    if market.account.required_for_search:
        flags.append("needs credentials")

    lines = [f"**{market.rank}. [{market.name}]({market.site})** — {' · '.join(flags)}", ""]
    if market.why:
        lines += ["> " + " ".join(market.why.split()), ""]
    if market.shipping.notes:
        lines += ["*Shipping:* " + " ".join(market.shipping.notes.split()), ""]
    if market.account.notes:
        lines += ["*Account:* " + " ".join(market.account.notes.split()), ""]
    return lines


if __name__ == "__main__":
    raise SystemExit(main())
